spring:
  h2:
    console:
      enabled: true
  profiles:
    group:
      production:
        - "dev"
        - "prod"
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: false
    change-log: classpath:db/changelog.xml