spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liquibase_prod?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml
server:
  port: 8081
