spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liquibase_dev?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml
server:
  port: 8080
