spring:
  profiles:
    group:
      production:
        - "dev"
        - "prod"
    active: prod
  datasource:
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver