server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/integration-test?createDatabaseIfNotExist=true
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
